### PR TITLE
Fix active users

### PR DESCRIPTION
**Pull request by sanjaysrikakulam**
I guess this would fix the [dahsboard](https://stats.galaxyproject.eu/d/000000004/galaxy?orgId=1&refresh=10s&viewPanel=107)

### CODE REVIEW

**Comment by bgruening** [comment]
If you do it this way, we need to find all occurrences of this panel on other sides. We can do that, but we need to be careful. E.g. the ELIXIR one and probably the ESG one has this panel as well.

**Comment by sanjaysrikakulam** [comment]
This dashboard is provisioned (I don't know how; I need to look into it) unlike the other ones you mentioned. They can be directly edited (I have already fixed the respective dashboards). This is only a fix for now. We have a dedicated grafana restructuring mini-project where we should look for stable solutions and fixes.

**Review by domgz — APPROVED** [review]
> If you do it this way, we need to find all occurrences of this panel on other sides. We can do that, but we need to be careful. E.g. the ELIXIR one and probably the ESG one has this panel as well.

If this is no longer a concern then it think it is fine, it looks now [exactly like the working panel](https://stats.galaxyproject.eu/d/xxeOsZiVz/elixir?orgId=1) from @mira-miracoli.

**Comment by bgruening** [comment]
Ok, lets try :) Thanks.

**Pull request merged**
